FROM lvvapflt.mirror.aliyuncs.com/library/node:16 as build

WORKDIR /abc
ADD . .

RUN yarn
ARG REACT_APP_DISABLED_FEATURES
ARG REACT_APP_VERSION
ARG ENV_MODE

RUN yarn build

FROM nginx:stable-alpine

COPY nginx.prod.conf /etc/nginx/nginx.conf

WORKDIR /abc
COPY --from=build /abc/build build